//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.27 at 11:36:30 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.javadude.org/trade", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.javadude.trade.request;
