
package org.javadude.trade;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TradeService", targetNamespace = "www.javadude.org/trade")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TradeService {


    /**
     * 
     * @param insertTradeRequest
     * @return
     *     returns org.javadude.trade.InsertTradeResponse
     */
    @WebMethod
    @WebResult(name = "insertTradeResponse", targetNamespace = "www.javadude.org/trade", partName = "insertTradeResponse")
    public InsertTradeResponse insertTrade(
        @WebParam(name = "insertTradeRequest", targetNamespace = "www.javadude.org/trade", partName = "insertTradeRequest")
        InsertTradeRequest insertTradeRequest);

}
