
package org.javadude.trade;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TradeServiceService", targetNamespace = "www.javadude.org/trade", wsdlLocation = "http://localhost:8082/trade-soap-service/trades.wsdl")
public class TradeServiceService
    extends Service
{

    private final static URL TRADESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TRADESERVICESERVICE_EXCEPTION;
    private final static QName TRADESERVICESERVICE_QNAME = new QName("www.javadude.org/trade", "TradeServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/trade-soap-service/trades.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRADESERVICESERVICE_WSDL_LOCATION = url;
        TRADESERVICESERVICE_EXCEPTION = e;
    }

    public TradeServiceService() {
        super(__getWsdlLocation(), TRADESERVICESERVICE_QNAME);
    }

    public TradeServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRADESERVICESERVICE_QNAME, features);
    }

    public TradeServiceService(URL wsdlLocation) {
        super(wsdlLocation, TRADESERVICESERVICE_QNAME);
    }

    public TradeServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRADESERVICESERVICE_QNAME, features);
    }

    public TradeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TradeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TradeService
     */
    @WebEndpoint(name = "TradeServiceSoap11")
    public TradeService getTradeServiceSoap11() {
        return super.getPort(new QName("www.javadude.org/trade", "TradeServiceSoap11"), TradeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TradeService
     */
    @WebEndpoint(name = "TradeServiceSoap11")
    public TradeService getTradeServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("www.javadude.org/trade", "TradeServiceSoap11"), TradeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRADESERVICESERVICE_EXCEPTION!= null) {
            throw TRADESERVICESERVICE_EXCEPTION;
        }
        return TRADESERVICESERVICE_WSDL_LOCATION;
    }

}
